mod_id=berlordsspellrestrictions
mod_name=Berlord's Spell Restrictions
mod_license=MIT
mod_version=0.1.0
mod_group_id=io.github.bertie_mc.spellrestrictions
mod_authors=berlord
mod_description=Discover scrolls to craft their spells. Unlock crafting rarity with orbs, and research special schools using manuscripts.
