mod_id=rusticengineerfix
mod_name=Rustic Engineer Fix
mod_license=Unlicense
mod_version=1.0.0
mod_group_id=io.github.bertie_mc.rusticengineerfix
mod_authors=berlord
mod_description=Fixes Rustic Engineer's dragonfly pitch-dive and choppy airship turning.
