mod_id=bertiecreatures
mod_name=Bertie Creatures
mod_license=GPL-3.0-only
mod_version=0.1.0
mod_group_id=io.github.bertie_mc.creatures
mod_authors=berlord, Alexthe668, Noonyeyz, Raguto
mod_description=Selected creatures and Thornwood from Alex's Caves, independently packaged for Bertie.
