mod_id=bertiefletching
mod_name=Bertie Fletching
mod_license=Unlicense
mod_version=0.2.1
mod_group_id=io.github.bertie_mc.fletching
mod_authors=berlord
mod_description=Eight-arrow batches, a potion reservoir, and combined arrow effects for Fletchery Expanded.
