package io.github.bertie_mc.alexscavesworldgenfix.worldgen;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.biome.Biome;

/**
 * The two Alex's Caves biomes whose structure pieces never pin themselves into the chunk.
 *
 * <p>Built by name rather than read from {@code ACBiomeRegistry}, so this mod still compiles and
 * loads with Alex's Caves absent. Nothing resolves these keys unless the matching structure piece
 * runs, which cannot happen without the mod that owns it.
 */
public final class AlexsCavesBiomes {

    private static final String NAMESPACE = "alexscaves";

    /** Generated by {@code FerrocaveStructurePiece}. */
    public static final ResourceKey<Biome> MAGNETIC_CAVES = key("magnetic_caves");

    /** Generated by {@code ForlornCanyonStructurePiece}. */
    public static final ResourceKey<Biome> FORLORN_HOLLOWS = key("forlorn_hollows");

    private AlexsCavesBiomes() {}

    private static ResourceKey<Biome> key(String path) {
        return ResourceKey.create(Registries.BIOME, ResourceLocation.fromNamespaceAndPath(NAMESPACE, path));
    }
}
