[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "ySnjMzLg"
version-id = "JMgVNypu"
filename = "accessories_compat_layer-neoforge-0.1.12+1.21.1.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "accessories-compat-layer"
project-id = 1315611
file-id = 7585673
filename = "accessories_compat_layer-neoforge-0.1.12+1.21.1.jar"
