[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "kK4odxRI"
version-id = "9F3QZPK4"
filename = "air-jump-enchantment-v1.0.2.jar"

[distributions.modrinth-datapack]
provider = "modrinth"
kind = "datapack"
project-id = "kK4odxRI"
version-id = "K5CcH2I7"
filename = "Air Jump Enchantment v1.0.2 [1.21-1.21.1].zip"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "air-jump-enchantment"
project-id = 1292199
file-id = 6823792
filename = "air-jump-enchantment-v1.0.2.jar"
