[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
side = "client"
project-id = "ZucWZEBV"
version-id = "RJgDIKSn"
filename = "better_climbing-neoforge-4.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
side = "client"
slug = "better-climbing"
project-id = 655619
file-id = 5514197
filename = "better_climbing-neoforge-4.jar"
