[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
side = "client"
project-id = "Q2OqKxDG"
version-id = "FjTYILOi"
filename = "BetterAdvancements-NeoForge-1.21.1-0.4.3.21.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
side = "client"
slug = "better-advancements"
project-id = 272515
file-id = 5850587
filename = "BetterAdvancements-NeoForge-1.21.1-0.4.3.21.jar"
