[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "4smC3lUy"
version-id = "hRHHud0R"
filename = "big_birch_tree-1.0.3-neoforge-1.21.1.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "big-birch-tree"
project-id = 1209852
file-id = 6789426
filename = "big_birch_tree-1.0.3-neoforge-1.21.1.jar"
