[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "7apv0bAM"
version-id = "nCs17mDT"
filename = "cataclysm_tools-2.0.0-neoforge-1.21.1.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "cataclysm-tools"
project-id = 1037520
file-id = 6709296
filename = "cataclysm_tools-2.0.0-neoforge-1.21.1.jar"
