[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "kgPopSTU"
version-id = "VHDEOhC6"
filename = "compactmachinespor-0.9.1.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "compactmachinespor"
project-id = 1534635
file-id = 8062363
filename = "compactmachinespor-0.9.1.jar"
