[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "Tg5fXO1x"
version-id = "1MPqh4Vt"
filename = "crafting_on_a_stick-1.21.0.4.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "crafting-on-a-stick"
project-id = 577850
file-id = 7394335
filename = "crafting_on_a_stick-1.21.0.4.jar"
