[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "gOQjCAAD"
version-id = "Ngn5DVCK"
filename = "cuisinedelight-1.2.8.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "cuisine-delight"
project-id = 893541
file-id = 8004724
filename = "cuisinedelight-1.2.8.jar"
