[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "9BgYgXE4"
version-id = "UzZnJKSR"
filename = "disenchanting_table-merged-1.21.1-5.0.2.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "dis-enchanting-table"
project-id = 933354
file-id = 6581607
filename = "disenchanting_table-merged-1.21.1-5.0.2.jar"
