[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
side = "client"
project-id = "LGVihYcz"
version-id = "wGOa5uxT"
filename = "EMIProfessions-neoforge-1.21.1-1.0.3.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
side = "client"
slug = "emi-professions-emip"
project-id = 1065904
file-id = 6231426
filename = "EMIProfessions-neoforge-1.21.1-1.0.3.jar"
