[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "TcYlOhqA"
version-id = "rr1QeaKo"
filename = "enderio_endergy-8.0.1-alpha.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "enderio-endergy"
project-id = 304346
file-id = 8017169
filename = "enderio_endergy-8.0.1-alpha.jar"
