[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "2uEhdGKt"
version-id = "DG541UlP"
filename = "endersdelight-1.3.0.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "enders-delight"
project-id = 827163
file-id = 8037557
filename = "endersdelight-1.3.0.jar"
