[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
side = "client"
project-id = "J5bVsBt9"
version-id = "cQKcPNVh"
filename = "enhancedbossbars-1.0.0.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
side = "client"
slug = "enhanced-boss-bars-mod"
project-id = 1063296
file-id = 7547171
filename = "enhancedbossbars-1.0.0.jar"
