[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "RV1qfVQ8"
version-id = "hIJ2Ev1Q"
filename = "ExplorersCompass-1.21.1-3.4.0-neoforge.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "explorers-compass"
project-id = 491794
file-id = 7892943
filename = "ExplorersCompass-1.21.1-3.4.0-neoforge.jar"
