[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "WEWiqYkW"
version-id = "lNMKoZrI"
filename = "exposure_polaroid-neoforge-1.21.1-1.1.4.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "exposure-polaroid"
project-id = 1207005
file-id = 8032504
filename = "exposure_polaroid-neoforge-1.21.1-1.1.4.jar"
