[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "yRrY3XII"
version-id = "XntyupDn"
filename = "extradelight-2.6.5.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "extradelight"
project-id = 842106
file-id = 8035753
filename = "extradelight-2.6.5.jar"
