[distributions.maven-mod]
provider = "maven"
kind = "mod"
module = "dev.ftb.mods:ftb-xmod-compat-neoforge"
version = "21.1.8"
filename = "ftb-xmod-compat-neoforge-21.1.8.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "ftb-xmod-compat"
project-id = 889915
file-id = 7715134
filename = "ftb-xmod-compat-neoforge-21.1.8.jar"
