[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "5OrL8C4a"
version-id = "tQhakMGs"
filename = "golemdungeons-2.0.9.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "golem-dungeons"
project-id = 1328313
file-id = 7903491
filename = "golemdungeons-2.0.9.jar"
