[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "24CSPS1E"
version-id = "Li2vsMel"
filename = "HorseExpert-v21.1.0-1.21.1-NeoForge.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "horse-expert"
project-id = 666942
file-id = 5731753
filename = "HorseExpert-v21.1.0-1.21.1-NeoForge.jar"
