[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "6bLUlbZn"
version-id = "ikdLP02G"
filename = "HostileNeuralNetworks-1.21.1-6.5.1.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "hostile-neural-networks"
project-id = 552574
file-id = 8525006
filename = "HostileNeuralNetworks-1.21.1-6.5.1.jar"
