[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
side = "server"
project-id = "KpICtuVx"
version-id = "TBI4EWjs"
filename = "incontrol-1.21-10.2.6.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
side = "server"
slug = "in-control"
project-id = 257356
file-id = 7436215
filename = "incontrol-1.21-10.2.6.jar"
