[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "LcafSQPm"
version-id = "pxvyXSjJ"
filename = "inventorio-mc1.21.1-neoforge-v1.11.0.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "inventorio"
project-id = 497122
file-id = 7268713
filename = "inventorio-mc1.21.1-neoforge-v1.11.0.jar"
