[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "s4OWxYQQ"
version-id = "AvHIYbZi"
filename = "irons_spellbooks-1.21.1-3.16.0.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "irons-spells-n-spellbooks"
project-id = 855414
file-id = 8202148
filename = "irons_spellbooks-1.21.1-3.16.0.jar"
