[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
side = "client"
project-id = "UaizcMKP"
version-id = "OrkSfQ0u"
filename = "item_descriptions-2.8.0+1.21.1-neoforge.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
side = "client"
slug = "item-descriptions"
project-id = 1101501
file-id = 8228839
filename = "item_descriptions-2.8.0+1.21.1-neoforge.jar"
