[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "9uQhkMe5"
version-id = "cjdV1zT2"
filename = "librarianlib-5.0.0-neoforge.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "librarianlib"
project-id = 252910
file-id = 6635493
filename = "librarianlib-5.0.0-neoforge.jar"
