[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "HUZkxNTQ"
version-id = "DsGsees0"
filename = "mekanism_extras-1.21.1-1.4.0.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "mekanism-extra"
project-id = 1026040
file-id = 7921191
filename = "mekanism_extras-1.21.1-1.4.0.jar"
