[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "qMxbM4BQ"
version-id = "YUHbwbgQ"
filename = "minersdelight-1.21.1-1.4.5.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "miners-delight"
project-id = 689630
file-id = 8011049
filename = "minersdelight-1.21.1-1.4.5.jar"
