[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
side = "client"
project-id = "QdG47OkI"
version-id = "X2U8ceG9"
filename = "modelfix-1.21-1.10.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
side = "client"
slug = "modelfix"
project-id = 676136
file-id = 5591286
filename = "modelfix-1.21-1.10.jar"
