[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "9RrPxPjq"
version-id = "CnMKioau"
filename = "modular_machinery_reborn_mekanism-1.21.1-3.0.3.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "modular-machinery-reborn-mekanism"
project-id = 1131856
file-id = 7731276
filename = "modular_machinery_reborn_mekanism-1.21.1-3.0.3.jar"
