[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "sUSfS0sK"
version-id = "koNg0E1I"
filename = "moreconcrete-neoforge-1.6.0-1.21.1.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "more-concrete"
project-id = 545354
file-id = 6359256
filename = "moreconcrete-neoforge-1.6.0-1.21.1.jar"
