[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "vI1QKJro"
version-id = "otPmhdts"
filename = "netherdepthsupgrade-3.1.8-1.21.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "nether-depths-upgrade"
project-id = 670011
file-id = 6430271
filename = "netherdepthsupgrade-3.1.8-1.21.jar"
