[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "aA94MQL4"
version-id = "S3poB44N"
filename = "PackagedAvaritia-Re-1.21.1-3.0.1.5.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "packagedavaritia"
project-id = 308383
file-id = 6828116
filename = "PackagedAvaritia-Re-1.21.1-3.0.1.5.jar"
