[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "IHyWDPnp"
version-id = "6tlFwckH"
filename = "perspatium-1.21.1-1.1.0.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "per-spatium"
project-id = 1164846
file-id = 6210685
filename = "perspatium-1.21.1-1.1.0.jar"
