[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "ZX66K16c"
version-id = "5NZounJc"
filename = "PickUpNotifier-v21.1.1-1.21.1-NeoForge.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "pick-up-notifier"
project-id = 351441
file-id = 6409785
filename = "PickUpNotifier-v21.1.1-1.21.1-NeoForge.jar"
