[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "M1953qlQ"
version-id = "lSbyRD6v"
filename = "resourcefulconfig-neoforge-1.21-3.0.11.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "resourceful-config"
project-id = 714059
file-id = 6467772
filename = "resourcefulconfig-neoforge-1.21-3.0.11.jar"
