[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "e0bNACJD"
version-id = "SPj5bJoM"
filename = "SereneSeasons-neoforge-1.21.1-10.1.0.3.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "serene-seasons"
project-id = 291874
file-id = 6182596
filename = "SereneSeasons-neoforge-1.21.1-10.1.0.3.jar"
