[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "5dUwdwpB"
version-id = "6mCe1UkK"
filename = "short_circuit-neoforge-1.21.1-1.0.9.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "short-circuit"
project-id = 1184318
file-id = 7511317
filename = "short_circuit-neoforge-1.21.1-1.0.9.jar"
