[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "r64P7w6f"
version-id = "iZ2EtzFd"
filename = "slavic_delight-0.3.2.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "slavic-delight"
project-id = 1092615
file-id = 7574034
filename = "slavic_delight-0.3.2.jar"
