[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "xq3wqd0E"
version-id = "jxID7Dx0"
filename = "sneak_through_berries-neoforge-21.1.0.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "sneak-through-berries"
project-id = 324945
file-id = 6564983
filename = "sneak_through_berries-neoforge-21.1.0.jar"
