[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
side = "client"
project-id = "TxIuhIFo"
version-id = "PPVE16f7"
filename = "statuseffectbars-1.21.1-NeoForge-1.0.2.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
side = "client"
slug = "status-effect-bars-reforged"
project-id = 1284599
file-id = 6707544
filename = "statuseffectbars-1.21.1-NeoForge-1.0.2.jar"
