[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "Koee7vhY"
version-id = "oJe8mlNE"
filename = "trailandtales_delight-0.4.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "trailtales-delight"
project-id = 1198527
file-id = 6526274
filename = "trailandtales_delight-0.4.jar"
