[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "4QrnfueM"
version-id = "qjxSupgx"
filename = "trashcans-1.0.18c-neoforge-mc1.21.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "trash-cans"
project-id = 394535
file-id = 5891067
filename = "trashcans-1.0.18c-neoforge-mc1.21.jar"
