[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
side = "client"
project-id = "yke6wdGF"
version-id = "701i2Xre"
filename = "tweakerge-0.4.3+mc1.21.1.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
side = "client"
slug = "tweakerge"
project-id = 915857
file-id = 7971130
filename = "tweakerge-0.4.3+mc1.21.1.jar"
