[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "twilight-forest-final-boss-remake"
project-id = 1267766
file-id = 7273092
filename = "twilight-forest-final-boss-remake-1267766-7273092.jar"
