[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "kpMfA312"
version-id = "fa0WBjoC"
filename = "universalgrid-neoforge-1.21.1-0.3.2.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "universal-grid"
project-id = 536160
file-id = 8145488
filename = "universalgrid-neoforge-1.21.1-0.3.2.jar"
