[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
project-id = "HsdNFinx"
version-id = "cttRekq9"
filename = "valhelsia_core-neoforge-1.21.1-1.1.4.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
slug = "valhelsia-core"
project-id = 416935
file-id = 5847440
filename = "valhelsia_core-neoforge-1.21.1-1.1.4.jar"
