[distributions.modrinth-mod]
provider = "modrinth"
kind = "mod"
side = "server"
project-id = "XNlO7sBv"
version-id = "GQ9iNWkI"
filename = "YungsBetterDesertTemples-1.21.1-NeoForge-4.1.5.jar"

[distributions.curseforge-mod]
provider = "curseforge"
kind = "mod"
side = "server"
slug = "yungs-better-desert-temples"
project-id = 1015114
file-id = 6276955
filename = "YungsBetterDesertTemples-1.21.1-NeoForge-4.1.5.jar"
