mod_id=witheringwaver
mod_name=Withering Waver
mod_license=Unlicense
mod_version=0.8.0
mod_group_id=io.github.bertie_mc.witheringwaver
mod_authors=berlord
mod_description=The Withering Waver - a rare wither skeleton variant for the bertie modpack.
