modLoader = "javafml"
loaderVersion = "[4,)"
license = "Unlicense"

[[mods]]
modId = "berlordsfoodsystemtest"
version = "1"
displayName = "Berlords Food System client tests"
description = "Test-only assertions for Berlords Food System"

[[dependencies.berlordsfoodsystemtest]]
modId = "berlordsfoodsystem"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.berlordsfoodsystemtest]]
modId = "sophisticatedcore"
type = "required"
versionRange = "[1.4,)"
ordering = "AFTER"
side = "CLIENT"
