mod_id=betterhorses
mod_name=Berlord's Better Horses
mod_license=Unlicense AND MIT
mod_version=0.1.0
mod_group_id=io.github.bertie_mc.betterhorses
mod_authors=berlord
mod_description=Horse effigies, horseshoes, appearance apples, netherite horse armor and specialist saddles.
