mod_id=enchantingrerollcost
mod_name=Enchanting Reroll Cost
mod_license=Unlicense
mod_version=1.0.0
mod_group_id=io.github.bertie_mc.enchantingrerollcost
mod_authors=berlord
mod_description=Scales Apothic enchanting rerolls to the minimum first-option XP price and one lapis lazuli.
