mod_id=fartbomb
game_test_namespace=minecraft
mod_name=Fart Bomb
mod_license=Unlicense
mod_version=1.3.0
mod_group_id=io.github.bertie_mc.fartbomb
mod_authors=berlord
mod_description=Fart Bomb - NeoForge 1.21.1 build for the bertie modpack.
