package io.github.bertie_mc.armorcompletions.client.models;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.LivingEntity;
/** New companion geometry for Cataclysm 3.31 / Minecraft 1.21.1. */
public class BoneReptileBootsModel<T extends LivingEntity> extends HumanoidModel<T> {
    public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(ResourceLocation.fromNamespaceAndPath("cataclysm", "bone_reptile_boots"), "main");
    public BoneReptileBootsModel(ModelPart root) {
        super(root);
        // Preserve the approved atlas UVs while shaping the armor geometry.
        ModelPart texturePart0 = root.getChild("right_leg").getChild("armorLeftBoot").getChild("boot_upper_texture_0");
        texturePart0.xScale = 1.09F;
        texturePart0.yScale = 1.09F;
        texturePart0.zScale = 1.09F;
        ModelPart texturePart1 = root.getChild("right_leg").getChild("armorLeftBoot").getChild("sole_texture_1");
        texturePart1.xScale = 1.06F;
        texturePart1.yScale = 1.24F;
        texturePart1.zScale = 1.048F;
        ModelPart texturePart2 = root.getChild("right_leg").getChild("armorLeftBoot").getChild("shin_gold_frame_texture_2");
        texturePart2.xScale = 1.03F;
        texturePart2.yScale = 3.12F;
        texturePart2.zScale = 0.28F;
        ModelPart texturePart3 = root.getChild("right_leg").getChild("armorLeftBoot").getChild("shin_bone_inlay_texture_3");
        texturePart3.xScale = 0.666667F;
        texturePart3.yScale = 0.666667F;
        texturePart3.zScale = 1.0F;
        ModelPart texturePart4 = root.getChild("right_leg").getChild("armorLeftBoot").getChild("ankle_band_texture_4");
        texturePart4.xScale = 1.16F;
        texturePart4.yScale = 1.64F;
        texturePart4.zScale = 1.16F;
        ModelPart texturePart5 = root.getChild("right_leg").getChild("armorLeftBoot").getChild("closed_gold_toe_texture_5");
        texturePart5.xScale = 1.04F;
        texturePart5.yScale = 2.16F;
        texturePart5.zScale = 0.79F;
        ModelPart texturePart6 = root.getChild("right_leg").getChild("armorLeftBoot").getChild("closed_bone_toe_texture_6");
        texturePart6.xScale = 1.02F;
        texturePart6.yScale = 0.353333F;
        texturePart6.zScale = 2.06F;
        ModelPart texturePart7 = root.getChild("right_leg").getChild("armorLeftBoot").getChild("toe_center_crest_texture_7");
        texturePart7.xScale = 0.25F;
        texturePart7.yScale = 1.0F;
        texturePart7.zScale = 0.5F;
        ModelPart texturePart8 = root.getChild("right_leg").getChild("armorLeftBoot").getChild("gold_heel_texture_8");
        texturePart8.xScale = 1.0F;
        texturePart8.yScale = 2.0F;
        texturePart8.zScale = 0.25F;
        ModelPart texturePart9 = root.getChild("right_leg").getChild("armorLeftBoot").getChild("armorLeftBoot_cube_9").getChild("outer_boot_guard_texture_0");
        texturePart9.xScale = 0.25F;
        texturePart9.yScale = 3.0F;
        texturePart9.zScale = 0.75F;
        ModelPart texturePart10 = root.getChild("left_leg").getChild("armorRightBoot").getChild("boot_upper_texture_0");
        texturePart10.xScale = 1.09F;
        texturePart10.yScale = 1.09F;
        texturePart10.zScale = 1.09F;
        ModelPart texturePart11 = root.getChild("left_leg").getChild("armorRightBoot").getChild("sole_texture_1");
        texturePart11.xScale = 1.06F;
        texturePart11.yScale = 1.24F;
        texturePart11.zScale = 1.048F;
        ModelPart texturePart12 = root.getChild("left_leg").getChild("armorRightBoot").getChild("shin_gold_frame_texture_2");
        texturePart12.xScale = 1.03F;
        texturePart12.yScale = 3.12F;
        texturePart12.zScale = 0.28F;
        ModelPart texturePart13 = root.getChild("left_leg").getChild("armorRightBoot").getChild("shin_bone_inlay_texture_3");
        texturePart13.xScale = 0.666667F;
        texturePart13.yScale = 0.666667F;
        texturePart13.zScale = 1.0F;
        ModelPart texturePart14 = root.getChild("left_leg").getChild("armorRightBoot").getChild("ankle_band_texture_4");
        texturePart14.xScale = 1.16F;
        texturePart14.yScale = 1.64F;
        texturePart14.zScale = 1.16F;
        ModelPart texturePart15 = root.getChild("left_leg").getChild("armorRightBoot").getChild("closed_gold_toe_texture_5");
        texturePart15.xScale = 1.04F;
        texturePart15.yScale = 2.16F;
        texturePart15.zScale = 0.79F;
        ModelPart texturePart16 = root.getChild("left_leg").getChild("armorRightBoot").getChild("closed_bone_toe_texture_6");
        texturePart16.xScale = 1.02F;
        texturePart16.yScale = 0.353333F;
        texturePart16.zScale = 2.06F;
        ModelPart texturePart17 = root.getChild("left_leg").getChild("armorRightBoot").getChild("toe_center_crest_texture_7");
        texturePart17.xScale = 0.25F;
        texturePart17.yScale = 1.0F;
        texturePart17.zScale = 0.5F;
        ModelPart texturePart18 = root.getChild("left_leg").getChild("armorRightBoot").getChild("gold_heel_texture_8");
        texturePart18.xScale = 1.0F;
        texturePart18.yScale = 2.0F;
        texturePart18.zScale = 0.25F;
        ModelPart texturePart19 = root.getChild("left_leg").getChild("armorRightBoot").getChild("armorRightBoot_cube_9").getChild("outer_boot_guard_texture_0");
        texturePart19.xScale = 0.25F;
        texturePart19.yScale = 3.0F;
        texturePart19.zScale = 0.75F;
    }
    public static LayerDefinition createArmorLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("head", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p1 = root.addOrReplaceChild("hat", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p2 = root.addOrReplaceChild("body", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p3 = root.addOrReplaceChild("right_arm", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p4 = root.addOrReplaceChild("left_arm", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p5 = root.addOrReplaceChild("right_leg", CubeListBuilder.create(), PartPose.offsetAndRotation(-2.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p6 = p5.addOrReplaceChild("armorLeftLeg", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p7 = p6.addOrReplaceChild("armorLeftLeg_cube_5", CubeListBuilder.create(), PartPose.offsetAndRotation(-1.9F, 1.5F, 0.0F, 0.0F, 0.0F, -0.305433F));
        PartDefinition p8 = p6.addOrReplaceChild("armorLeftLeg_cube_6", CubeListBuilder.create(), PartPose.offsetAndRotation(-1.9F, 1.5F, 0.0F, 0.0F, 0.0F, -0.305433F));
        PartDefinition p9 = p6.addOrReplaceChild("armorLeftLeg_cube_7", CubeListBuilder.create(), PartPose.offsetAndRotation(-1.9F, 1.5F, 0.0F, 0.0F, 0.0F, -0.305433F));
        PartDefinition p10 = p6.addOrReplaceChild("armorLeftLeg_cube_12", CubeListBuilder.create(), PartPose.offsetAndRotation(-2.0F, 8.0F, 0.0F, 0.0F, 0.0F, -0.349066F));
        PartDefinition p11 = p5.addOrReplaceChild("armorLeftBoot", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        p11.addOrReplaceChild("boot_upper_texture_0", CubeListBuilder.create().texOffs(93, 8).addBox(0.0F, 0.0F, 0.0F, 4.0F, 4.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.18F, 7.82F, -2.18F));
        p11.addOrReplaceChild("sole_texture_1", CubeListBuilder.create().texOffs(83, 18).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 5.0F, CubeDeformation.NONE), PartPose.offset(-2.12F, 11.18F, -3.12F));
        p11.addOrReplaceChild("shin_gold_frame_texture_2", CubeListBuilder.create().texOffs(111, 13).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.06F, 8.14F, -2.91F));
        p11.addOrReplaceChild("shin_bone_inlay_texture_3", CubeListBuilder.create().texOffs(83, 10).addBox(0.0F, 0.0F, 0.0F, 3.0F, 3.0F, 1.0F, CubeDeformation.NONE), PartPose.offset(-1.0F, 8.7F, -3.18F));
        p11.addOrReplaceChild("ankle_band_texture_4", CubeListBuilder.create().texOffs(111, 13).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.32F, 7.48F, -2.32F));
        p11.addOrReplaceChild("closed_gold_toe_texture_5", CubeListBuilder.create().texOffs(111, 13).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.08F, 9.57F, -3.88F));
        p11.addOrReplaceChild("closed_bone_toe_texture_6", CubeListBuilder.create().texOffs(83, 10).addBox(0.0F, 0.0F, 0.0F, 3.0F, 3.0F, 1.0F, CubeDeformation.NONE), PartPose.offset(-1.53F, 10.07F, -4.08F));
        p11.addOrReplaceChild("toe_center_crest_texture_7", CubeListBuilder.create().texOffs(111, 13).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-0.5F, 9.55F, -3.85F));
        p11.addOrReplaceChild("gold_heel_texture_8", CubeListBuilder.create().texOffs(111, 13).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.0F, 9.35F, 1.45F));
        PartDefinition p12 = p11.addOrReplaceChild("armorLeftBoot_cube_9", CubeListBuilder.create(), PartPose.offsetAndRotation(-2.0F, 9.5F, 0.0F, 0.0F, 0.0F, -0.218166F));
        p12.addOrReplaceChild("outer_boot_guard_texture_0", CubeListBuilder.create().texOffs(111, 13).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-0.9F, -1.6F, -1.25F));
        PartDefinition p13 = root.addOrReplaceChild("left_leg", CubeListBuilder.create(), PartPose.offsetAndRotation(2.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p14 = p13.addOrReplaceChild("armorRightLeg", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p15 = p14.addOrReplaceChild("armorRightLeg_cube_5", CubeListBuilder.create(), PartPose.offsetAndRotation(1.9F, 1.5F, 0.0F, 0.0F, 0.0F, 0.305433F));
        PartDefinition p16 = p14.addOrReplaceChild("armorRightLeg_cube_6", CubeListBuilder.create(), PartPose.offsetAndRotation(1.9F, 1.5F, 0.0F, 0.0F, 0.0F, 0.305433F));
        PartDefinition p17 = p14.addOrReplaceChild("armorRightLeg_cube_7", CubeListBuilder.create(), PartPose.offsetAndRotation(1.9F, 1.5F, 0.0F, 0.0F, 0.0F, 0.305433F));
        PartDefinition p18 = p14.addOrReplaceChild("armorRightLeg_cube_12", CubeListBuilder.create(), PartPose.offsetAndRotation(2.0F, 8.0F, 0.0F, 0.0F, 0.0F, 0.349066F));
        PartDefinition p19 = p13.addOrReplaceChild("armorRightBoot", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        p19.addOrReplaceChild("boot_upper_texture_0", CubeListBuilder.create().texOffs(93, 8).addBox(0.0F, 0.0F, 0.0F, 4.0F, 4.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.18F, 7.82F, -2.18F));
        p19.addOrReplaceChild("sole_texture_1", CubeListBuilder.create().texOffs(83, 18).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 5.0F, CubeDeformation.NONE), PartPose.offset(-2.12F, 11.18F, -3.12F));
        p19.addOrReplaceChild("shin_gold_frame_texture_2", CubeListBuilder.create().texOffs(111, 13).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.06F, 8.14F, -2.91F));
        p19.addOrReplaceChild("shin_bone_inlay_texture_3", CubeListBuilder.create().texOffs(83, 10).addBox(0.0F, 0.0F, 0.0F, 3.0F, 3.0F, 1.0F, CubeDeformation.NONE), PartPose.offset(-1.0F, 8.7F, -3.18F));
        p19.addOrReplaceChild("ankle_band_texture_4", CubeListBuilder.create().texOffs(111, 13).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.32F, 7.48F, -2.32F));
        p19.addOrReplaceChild("closed_gold_toe_texture_5", CubeListBuilder.create().texOffs(111, 13).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.08F, 9.57F, -3.88F));
        p19.addOrReplaceChild("closed_bone_toe_texture_6", CubeListBuilder.create().texOffs(83, 10).addBox(0.0F, 0.0F, 0.0F, 3.0F, 3.0F, 1.0F, CubeDeformation.NONE), PartPose.offset(-1.53F, 10.07F, -4.08F));
        p19.addOrReplaceChild("toe_center_crest_texture_7", CubeListBuilder.create().texOffs(111, 13).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-0.5F, 9.55F, -3.85F));
        p19.addOrReplaceChild("gold_heel_texture_8", CubeListBuilder.create().texOffs(111, 13).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.0F, 9.35F, 1.45F));
        PartDefinition p20 = p19.addOrReplaceChild("armorRightBoot_cube_9", CubeListBuilder.create(), PartPose.offsetAndRotation(2.0F, 9.5F, 0.0F, 0.0F, 0.0F, 0.218166F));
        p20.addOrReplaceChild("outer_boot_guard_texture_0", CubeListBuilder.create().texOffs(111, 13).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-0.1F, -1.6F, -1.25F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
