package io.github.bertie_mc.armorcompletions.client.models;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.LivingEntity;
/** New companion geometry for Cataclysm 3.31 / Minecraft 1.21.1. */
public class BoneReptileLeggingsModel<T extends LivingEntity> extends HumanoidModel<T> {
    public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(ResourceLocation.fromNamespaceAndPath("cataclysm", "bone_reptile_leggings"), "main");
    public BoneReptileLeggingsModel(ModelPart root) {
        super(root);
        // Preserve the approved atlas UVs while shaping the armor geometry.
        ModelPart texturePart0 = root.getChild("right_leg").getChild("armorLeftLeg").getChild("trouser_texture_0");
        texturePart0.xScale = 1.065F;
        texturePart0.yScale = 1.021667F;
        texturePart0.zScale = 1.065F;
        ModelPart texturePart1 = root.getChild("right_leg").getChild("armorLeftLeg").getChild("waist_band_texture_1");
        texturePart1.xScale = 1.15F;
        texturePart1.yScale = 1.6F;
        texturePart1.zScale = 1.15F;
        ModelPart texturePart2 = root.getChild("right_leg").getChild("armorLeftLeg").getChild("thigh_gold_frame_texture_2");
        texturePart2.xScale = 1.03F;
        texturePart2.yScale = 5.12F;
        texturePart2.zScale = 0.28F;
        ModelPart texturePart3 = root.getChild("right_leg").getChild("armorLeftLeg").getChild("thigh_bone_inlay_texture_3");
        texturePart3.xScale = 1.0F;
        texturePart3.yScale = 1.0F;
        texturePart3.zScale = 1.0F;
        ModelPart texturePart4 = root.getChild("right_leg").getChild("armorLeftLeg").getChild("thigh_center_ridge_texture_4");
        texturePart4.xScale = 0.333333F;
        texturePart4.yScale = 1.0F;
        texturePart4.zScale = 1.0F;
        ModelPart texturePart5 = root.getChild("right_leg").getChild("armorLeftLeg").getChild("lower_thigh_band_texture_5");
        texturePart5.xScale = 1.13F;
        texturePart5.yScale = 1.52F;
        texturePart5.zScale = 1.13F;
        ModelPart texturePart6 = root.getChild("right_leg").getChild("armorLeftLeg").getChild("knee_gold_shield_texture_6");
        texturePart6.xScale = 1.04F;
        texturePart6.yScale = 3.16F;
        texturePart6.zScale = 0.29F;
        ModelPart texturePart7 = root.getChild("right_leg").getChild("armorLeftLeg").getChild("knee_bone_crest_texture_7");
        texturePart7.xScale = 0.666667F;
        texturePart7.yScale = 0.5F;
        texturePart7.zScale = 1.0F;
        ModelPart texturePart8 = root.getChild("right_leg").getChild("armorLeftLeg").getChild("knee_gold_keel_texture_8");
        texturePart8.xScale = 0.25F;
        texturePart8.yScale = 2.0F;
        texturePart8.zScale = 0.25F;
        ModelPart texturePart9 = root.getChild("right_leg").getChild("armorLeftLeg").getChild("armorLeftLeg_cube_5").getChild("flared_hip_frame_texture_0");
        texturePart9.xScale = 0.25F;
        texturePart9.yScale = 5.0F;
        texturePart9.zScale = 1.25F;
        ModelPart texturePart10 = root.getChild("right_leg").getChild("armorLeftLeg").getChild("armorLeftLeg_cube_6").getChild("hip_bone_relief_texture_0");
        texturePart10.xScale = 0.333333F;
        texturePart10.yScale = 1.0F;
        texturePart10.zScale = 3.0F;
        ModelPart texturePart11 = root.getChild("right_leg").getChild("armorLeftLeg").getChild("armorLeftLeg_cube_7").getChild("hip_crest_texture_0");
        texturePart11.xScale = 0.25F;
        texturePart11.yScale = 2.0F;
        texturePart11.zScale = 0.75F;
        ModelPart texturePart12 = root.getChild("right_leg").getChild("armorLeftLeg").getChild("armorLeftLeg_cube_12").getChild("outer_knee_spur_texture_0");
        texturePart12.xScale = 0.333333F;
        texturePart12.yScale = 0.5F;
        texturePart12.zScale = 3.0F;
        ModelPart texturePart13 = root.getChild("left_leg").getChild("armorRightLeg").getChild("trouser_texture_0");
        texturePart13.xScale = 1.065F;
        texturePart13.yScale = 1.021667F;
        texturePart13.zScale = 1.065F;
        ModelPart texturePart14 = root.getChild("left_leg").getChild("armorRightLeg").getChild("waist_band_texture_1");
        texturePart14.xScale = 1.15F;
        texturePart14.yScale = 1.6F;
        texturePart14.zScale = 1.15F;
        ModelPart texturePart15 = root.getChild("left_leg").getChild("armorRightLeg").getChild("thigh_gold_frame_texture_2");
        texturePart15.xScale = 1.03F;
        texturePart15.yScale = 5.12F;
        texturePart15.zScale = 0.28F;
        ModelPart texturePart16 = root.getChild("left_leg").getChild("armorRightLeg").getChild("thigh_bone_inlay_texture_3");
        texturePart16.xScale = 1.0F;
        texturePart16.yScale = 1.0F;
        texturePart16.zScale = 1.0F;
        ModelPart texturePart17 = root.getChild("left_leg").getChild("armorRightLeg").getChild("thigh_center_ridge_texture_4");
        texturePart17.xScale = 0.333333F;
        texturePart17.yScale = 1.0F;
        texturePart17.zScale = 1.0F;
        ModelPart texturePart18 = root.getChild("left_leg").getChild("armorRightLeg").getChild("lower_thigh_band_texture_5");
        texturePart18.xScale = 1.13F;
        texturePart18.yScale = 1.52F;
        texturePart18.zScale = 1.13F;
        ModelPart texturePart19 = root.getChild("left_leg").getChild("armorRightLeg").getChild("knee_gold_shield_texture_6");
        texturePart19.xScale = 1.04F;
        texturePart19.yScale = 3.16F;
        texturePart19.zScale = 0.29F;
        ModelPart texturePart20 = root.getChild("left_leg").getChild("armorRightLeg").getChild("knee_bone_crest_texture_7");
        texturePart20.xScale = 0.666667F;
        texturePart20.yScale = 0.5F;
        texturePart20.zScale = 1.0F;
        ModelPart texturePart21 = root.getChild("left_leg").getChild("armorRightLeg").getChild("knee_gold_keel_texture_8");
        texturePart21.xScale = 0.25F;
        texturePart21.yScale = 2.0F;
        texturePart21.zScale = 0.25F;
        ModelPart texturePart22 = root.getChild("left_leg").getChild("armorRightLeg").getChild("armorRightLeg_cube_5").getChild("flared_hip_frame_texture_0");
        texturePart22.xScale = 0.25F;
        texturePart22.yScale = 5.0F;
        texturePart22.zScale = 1.25F;
        ModelPart texturePart23 = root.getChild("left_leg").getChild("armorRightLeg").getChild("armorRightLeg_cube_6").getChild("hip_bone_relief_texture_0");
        texturePart23.xScale = 0.333333F;
        texturePart23.yScale = 1.0F;
        texturePart23.zScale = 3.0F;
        ModelPart texturePart24 = root.getChild("left_leg").getChild("armorRightLeg").getChild("armorRightLeg_cube_7").getChild("hip_crest_texture_0");
        texturePart24.xScale = 0.25F;
        texturePart24.yScale = 2.0F;
        texturePart24.zScale = 0.75F;
        ModelPart texturePart25 = root.getChild("left_leg").getChild("armorRightLeg").getChild("armorRightLeg_cube_12").getChild("outer_knee_spur_texture_0");
        texturePart25.xScale = 0.333333F;
        texturePart25.yScale = 0.5F;
        texturePart25.zScale = 3.0F;
    }
    public static LayerDefinition createArmorLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("head", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p1 = root.addOrReplaceChild("hat", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p2 = root.addOrReplaceChild("body", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p3 = root.addOrReplaceChild("right_arm", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p4 = root.addOrReplaceChild("left_arm", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p5 = root.addOrReplaceChild("right_leg", CubeListBuilder.create(), PartPose.offsetAndRotation(-2.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p6 = p5.addOrReplaceChild("armorLeftLeg", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        p6.addOrReplaceChild("trouser_texture_0", CubeListBuilder.create().texOffs(65, 1).addBox(0.0F, 0.0F, 0.0F, 4.0F, 12.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.13F, -0.13F, -2.13F));
        p6.addOrReplaceChild("waist_band_texture_1", CubeListBuilder.create().texOffs(111, 6).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.3F, -0.3F, -2.3F));
        p6.addOrReplaceChild("thigh_gold_frame_texture_2", CubeListBuilder.create().texOffs(93, 1).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.06F, 0.84F, -2.96F));
        p6.addOrReplaceChild("thigh_bone_inlay_texture_3", CubeListBuilder.create().texOffs(25, 1).addBox(0.0F, 0.0F, 0.0F, 3.0F, 4.0F, 1.0F, CubeDeformation.NONE), PartPose.offset(-1.5F, 1.4F, -3.18F));
        p6.addOrReplaceChild("thigh_center_ridge_texture_4", CubeListBuilder.create().texOffs(25, 1).addBox(0.0F, 0.0F, 0.0F, 3.0F, 4.0F, 1.0F, CubeDeformation.NONE), PartPose.offset(-0.5F, 1.6F, -3.4F));
        p6.addOrReplaceChild("lower_thigh_band_texture_5", CubeListBuilder.create().texOffs(93, 1).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.26F, 5.04F, -2.26F));
        p6.addOrReplaceChild("knee_gold_shield_texture_6", CubeListBuilder.create().texOffs(93, 1).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.08F, 5.92F, -3.13F));
        p6.addOrReplaceChild("knee_bone_crest_texture_7", CubeListBuilder.create().texOffs(25, 1).addBox(0.0F, 0.0F, 0.0F, 3.0F, 4.0F, 1.0F, CubeDeformation.NONE), PartPose.offset(-1.0F, 6.6F, -3.45F));
        p6.addOrReplaceChild("knee_gold_keel_texture_8", CubeListBuilder.create().texOffs(93, 1).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-0.5F, 7.45F, -3.5F));
        PartDefinition p7 = p6.addOrReplaceChild("armorLeftLeg_cube_5", CubeListBuilder.create(), PartPose.offsetAndRotation(-1.9F, 1.5F, 0.0F, 0.0F, 0.0F, -0.305433F));
        p7.addOrReplaceChild("flared_hip_frame_texture_0", CubeListBuilder.create().texOffs(93, 1).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-1.0F, -0.8F, -2.5F));
        PartDefinition p8 = p6.addOrReplaceChild("armorLeftLeg_cube_6", CubeListBuilder.create(), PartPose.offsetAndRotation(-1.9F, 1.5F, 0.0F, 0.0F, 0.0F, -0.305433F));
        p8.addOrReplaceChild("hip_bone_relief_texture_0", CubeListBuilder.create().texOffs(25, 1).addBox(0.0F, 0.0F, 0.0F, 3.0F, 4.0F, 1.0F, CubeDeformation.NONE), PartPose.offset(-1.3F, -0.3F, -1.5F));
        PartDefinition p9 = p6.addOrReplaceChild("armorLeftLeg_cube_7", CubeListBuilder.create(), PartPose.offsetAndRotation(-1.9F, 1.5F, 0.0F, 0.0F, 0.0F, -0.305433F));
        p9.addOrReplaceChild("hip_crest_texture_0", CubeListBuilder.create().texOffs(93, 1).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-1.35F, -1.6F, -1.5F));
        PartDefinition p10 = p6.addOrReplaceChild("armorLeftLeg_cube_12", CubeListBuilder.create(), PartPose.offsetAndRotation(-2.0F, 8.0F, 0.0F, 0.0F, 0.0F, -0.349066F));
        p10.addOrReplaceChild("outer_knee_spur_texture_0", CubeListBuilder.create().texOffs(25, 1).addBox(0.0F, 0.0F, 0.0F, 3.0F, 4.0F, 1.0F, CubeDeformation.NONE), PartPose.offset(-0.8F, -1.6F, -2.5F));
        PartDefinition p11 = p5.addOrReplaceChild("armorLeftBoot", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p12 = p11.addOrReplaceChild("armorLeftBoot_cube_9", CubeListBuilder.create(), PartPose.offsetAndRotation(-2.0F, 9.5F, 0.0F, 0.0F, 0.0F, -0.218166F));
        PartDefinition p13 = root.addOrReplaceChild("left_leg", CubeListBuilder.create(), PartPose.offsetAndRotation(2.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p14 = p13.addOrReplaceChild("armorRightLeg", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        p14.addOrReplaceChild("trouser_texture_0", CubeListBuilder.create().texOffs(65, 1).addBox(0.0F, 0.0F, 0.0F, 4.0F, 12.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.13F, -0.13F, -2.13F));
        p14.addOrReplaceChild("waist_band_texture_1", CubeListBuilder.create().texOffs(111, 6).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.3F, -0.3F, -2.3F));
        p14.addOrReplaceChild("thigh_gold_frame_texture_2", CubeListBuilder.create().texOffs(93, 1).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.06F, 0.84F, -2.96F));
        p14.addOrReplaceChild("thigh_bone_inlay_texture_3", CubeListBuilder.create().texOffs(25, 1).addBox(0.0F, 0.0F, 0.0F, 3.0F, 4.0F, 1.0F, CubeDeformation.NONE), PartPose.offset(-1.5F, 1.4F, -3.18F));
        p14.addOrReplaceChild("thigh_center_ridge_texture_4", CubeListBuilder.create().texOffs(25, 1).addBox(0.0F, 0.0F, 0.0F, 3.0F, 4.0F, 1.0F, CubeDeformation.NONE), PartPose.offset(-0.5F, 1.6F, -3.4F));
        p14.addOrReplaceChild("lower_thigh_band_texture_5", CubeListBuilder.create().texOffs(93, 1).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.26F, 5.04F, -2.26F));
        p14.addOrReplaceChild("knee_gold_shield_texture_6", CubeListBuilder.create().texOffs(93, 1).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-2.08F, 5.92F, -3.13F));
        p14.addOrReplaceChild("knee_bone_crest_texture_7", CubeListBuilder.create().texOffs(25, 1).addBox(0.0F, 0.0F, 0.0F, 3.0F, 4.0F, 1.0F, CubeDeformation.NONE), PartPose.offset(-1.0F, 6.6F, -3.45F));
        p14.addOrReplaceChild("knee_gold_keel_texture_8", CubeListBuilder.create().texOffs(93, 1).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(-0.5F, 7.45F, -3.5F));
        PartDefinition p15 = p14.addOrReplaceChild("armorRightLeg_cube_5", CubeListBuilder.create(), PartPose.offsetAndRotation(1.9F, 1.5F, 0.0F, 0.0F, 0.0F, 0.305433F));
        p15.addOrReplaceChild("flared_hip_frame_texture_0", CubeListBuilder.create().texOffs(93, 1).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(0.0F, -0.8F, -2.5F));
        PartDefinition p16 = p14.addOrReplaceChild("armorRightLeg_cube_6", CubeListBuilder.create(), PartPose.offsetAndRotation(1.9F, 1.5F, 0.0F, 0.0F, 0.0F, 0.305433F));
        p16.addOrReplaceChild("hip_bone_relief_texture_0", CubeListBuilder.create().texOffs(25, 1).addBox(0.0F, 0.0F, 0.0F, 3.0F, 4.0F, 1.0F, CubeDeformation.NONE), PartPose.offset(0.3F, -0.3F, -1.5F));
        PartDefinition p17 = p14.addOrReplaceChild("armorRightLeg_cube_7", CubeListBuilder.create(), PartPose.offsetAndRotation(1.9F, 1.5F, 0.0F, 0.0F, 0.0F, 0.305433F));
        p17.addOrReplaceChild("hip_crest_texture_0", CubeListBuilder.create().texOffs(93, 1).addBox(0.0F, 0.0F, 0.0F, 4.0F, 1.0F, 4.0F, CubeDeformation.NONE), PartPose.offset(0.35F, -1.6F, -1.5F));
        PartDefinition p18 = p14.addOrReplaceChild("armorRightLeg_cube_12", CubeListBuilder.create(), PartPose.offsetAndRotation(2.0F, 8.0F, 0.0F, 0.0F, 0.0F, 0.349066F));
        p18.addOrReplaceChild("outer_knee_spur_texture_0", CubeListBuilder.create().texOffs(25, 1).addBox(0.0F, 0.0F, 0.0F, 3.0F, 4.0F, 1.0F, CubeDeformation.NONE), PartPose.offset(-0.2F, -1.6F, -2.5F));
        PartDefinition p19 = p13.addOrReplaceChild("armorRightBoot", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p20 = p19.addOrReplaceChild("armorRightBoot_cube_9", CubeListBuilder.create(), PartPose.offsetAndRotation(2.0F, 9.5F, 0.0F, 0.0F, 0.0F, 0.218166F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
