modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "Unlicense"

[[mods]]
modId = "bertie_gametest_driver"
version = "1"
displayName = "Bertie GameTest driver"
description = "Connects native Minecraft GameTests to Bertie's Gradle reports."

[[dependencies."bertie_gametest_driver"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."bertie_gametest_driver"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
