mod_id=bertie_progression
archive_name=bertie-progression
mod_name=Bertie Progression
mod_license=Unlicense
mod_version=0.25.2
mod_group_id=com.berlord.bertie_progression
mod_authors=berlord
mod_description=The progression mod for the bertie modpack, integrating custom items, gated crafting, recipes, and cross-mod systems into a coherent experience.
