mod_id=bertieprogression
archive_name=bertieprogression
mod_name=Bertie Progression
mod_license=Unlicense
mod_version=0.27.0
mod_group_id=io.github.bertie_mc.bertieprogression
mod_authors=berlord
mod_description=The progression mod for the bertie modpack, integrating custom items, gated crafting, recipes, and cross-mod systems into a coherent experience.
