mod_id=hephaestusarchitecture
mod_name=Bertie Hephaestus Architecture
mod_license=Unlicense
mod_version=0.2.0
mod_group_id=io.github.bertie_mc.hephaestusarchitecture
mod_authors=berlord
mod_description=Tier-specific multiblock layouts and expanded pedestal routing for the Forbidden and Arcanus Hephaestus Forge.
