mod_id=voidfog
mod_name=Void Fog
mod_license=Unlicense
mod_version=0.7.0
mod_group_id=io.github.bertie_mc.voidfog
mod_authors=berlord
mod_description=Brings back the void fog the game drew near the world floor before 1.8, per dimension.
