mod_id=creeperoverhaulfix
mod_name=Creeper Overhaul Fix
mod_license=Unlicense
mod_version=1.0.0
mod_group_id=io.github.bertie_mc.creeperoverhaulfix
mod_authors=berlord
mod_description=Stops Creeper Overhaul's tiny cactus from occluding its neighbours, which made the ground under a placed cactus disappear.
