modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${client_test_mod_id}"
version = "${client_test_mod_version}"
displayName = "${client_test_mod_name}"
description = "${client_test_mod_description}"

[[dependencies."${client_test_mod_id}"]]
modId = "${mod_id}"
type = "required"
versionRange = "[2,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies."${client_test_mod_id}"]]
modId = "immersive_armors"
type = "required"
versionRange = "[1.7,)"
ordering = "AFTER"
side = "CLIENT"
