plugins {
    id("bertie.pack")
    id("bertie.gametest")
    id("bertie.client-test")
}

dependencies {
    packMods(project(":mods:berlords-carving"))
    packMods(project(":mods:berlords-food-system"))
    packMods(project(":mods:bertie-blackhole"))
    packMods(project(":mods:bertie-emi"))
    packMods(project(":mods:bertie-filters"))
    packMods(project(":mods:bertie-progression"))
    packMods(project(":mods:bertie-tiers"))
    packMods(project(":mods:bertie-weapons"))
    packMods(project(":mods:bush-tweaks"))
    packMods(project(":mods:config-migrations"))
    packMods(project(":mods:ender-eyes"))
    packMods(project(":mods:explode-to-mine"))
    packMods(project(":mods:fart-bomb"))
    packMods(project(":mods:forge-ink"))
    packMods(project(":mods:frozen-reg-fix"))
    packMods(project(":mods:hephaestus-architecture"))
    packMods(project(":mods:primitive-refined"))
    packMods(project(":mods:rustic-engineer-fix"))
    packMods(project(":mods:explosive-enhancement"))
    packMods(project(":mods:fd-shader-fix"))
    packMods(project(":mods:screenshot-copy"))
    packMods(project(":mods:short-circuit-fix"))
    packMods(project(":mods:withered-hearts"))
}
