name = "bertie"
author = "berlord"
version = "0.1.0"
description = "An exploration, technology, and magic modpack for NeoForge 1.21.1."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ac530f24ad9dc3bb56d7e21ad276d95b272b277555b735c60095f468a6710ff"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
