name = "bertie"
author = "berlord"
version = "0.1.0"
description = "An exploration, technology, and magic modpack for NeoForge 1.21.1."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f2325287c9fe736c765bd00c7824246b865f5f007b9a15d7fee5009842d31bf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
