mod_id=screenshotcopy
mod_name=Bertie Screenshot Copy
mod_license=Unlicense
mod_version=1.0.0
mod_group_id=io.github.bertie_mc.screenshotcopy
mod_authors=berlord
mod_description=Copies Minecraft screenshots to the native desktop clipboard without AWT.
