mod_id=cooparticlesfix
mod_name=CooParticles API Dedicated Server Fix
mod_license=Unlicense
mod_version=1.0.0
mod_group_id=io.github.bertie_mc.cooparticlesfix
mod_authors=berlord
mod_description=Prevents CooParticles API from reflecting over its client-only test listener on dedicated servers.
