modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license} (code); see NOTICE for artwork"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "irons_spellbooks"
type = "required"
versionRange = "[1.21.1-3.16.0,1.21.1-4)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "irons_restrictions"
type = "incompatible"
versionRange = "[0,)"
reason = "The two mods implement conflicting spell progression rules."
side = "BOTH"
